### ISSUE TITLE
Documentation is inexistent.

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectB_Group7#29]
I don't care if we are post delivery, this one should be settled yes or yes.

An explaination on how to import the package and how to use it is like the **least** that can be done and it doesn't take more than 15 minutes. I don't even know how noone can have thought of this.

(I'm not in a good mood. Just letting you know :laughing: )

**Comment by sacdallago** [comment]
Wrong alex @AlexBeischl :dancer:

**Comment by AlexMoroz** [comment]
https://github.com/Rostlab/JS16_ProjectB_Group7/blob/develop/README.md
@nicoladesocio @dan736923 @konstantinos-angelo 
Documentation?

**Comment by nicoladesocio** [comment]
Check the wiki

**Comment by AlexMoroz** [comment]
oh, nice, so we can close this
