### ISSUE TITLE
Don't commit on develop

### ISSUE THREAD

**Issue by AlexMoroz** [Rostlab/JS16_ProjectB_Group7#4]
https://github.com/Rostlab/JS16_ProjectC_Group10/issues/1

**Comment by AlexMoroz** [comment]
and https://github.com/Rostlab/JS16_ProjectC_Group10/issues/4

**Comment by sacdallago** [comment]
Thanks @AlexMoroz for taking care of this, very correct!

@nicoladesocio please use the feature model with Pull Requests, close this issue if you have read this and understood, otherwise ask your team mates, @AlexMoroz or me for help.

**Comment by nicoladesocio** [comment]
read and understood, I should have reverted the develop branch correctly
