### ISSUE TITLE
Are you providing a frontend?

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectB_Group7#6]
Are you providing a frontend for your PLOD of a single character or do you provide us (ProjectF) with the corresponding data and its our task to display them? 

cc @jorjo1 @yashha

**Comment by k-angelo** [comment]
That is up to debate on whatever works best for you.
Generally we are still discussing about this with group 6 also as there are no strict requirements about our deliverable. Our idea is to provide a character with a PLOD statistic as well as using d3js library to make the top 10 graphic representation.

So our in response to your question, I in turn ask what would be more convenient for you:
a) raw percentages so you can do your own manipulation along with a say top10 JSON call from the server, 
b) produce some kind of raw html code that you can somehow embed in your page (<div>[d3 logic] </div>)

Personally I would prefer to only give you raw data and maybe give you an example of how the d3 will be run on the page as that would be the easiest thing for both parties to integrate ?
Take into account that there are 2 parties currently working on independent statistics and it's still up to discussion how these can be combined into a single page (maybe a mean average).

We can discuss after the presentations if you like.

**Comment by sacdallago** [comment]
> Personally I would prefer to only give you raw data and maybe give you an example of how the d3 will be run on the page as that would be the easiest thing for both parties to integrate ?

This is also my preference.

**Comment by sacdallago** [comment]
I rectify: not only my preference, it's gonna be what you will do. :dancer: Hope it's democratic enough :laughing:
