### ISSUE TITLE
Build is failing.

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectB_Group7#8]
Please check your code before pushing it and opening pull-requests. You've got like 2 layers of protection before pulling nonsense code and yet you still manage to push stuff that brakes Travis

**Comment by AlexMoroz** [comment]
#3 This one was open 10 days ago. Still no reaction.

**Comment by sacdallago** [comment]
I remember :)

**Comment by sacdallago** [comment]
But I'm more **official**

**Comment by dan736923** [comment]
fixed
