### ISSUE TITLE
Project Package via NPM 

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectB_Group7#9]
Please provide your NPM package as soon as possible!

**Comment by AlexMoroz** [comment]
Please, create js file like this in the root folder:

```
(function() {
    // do something 
    return result;
})();
```

After it appears, I will configured a package and it will be published automatically.

**Comment by nicoladesocio** [comment]
sorry, probabily it's a silly / alredy answered question. We need to give you a javascriot object with names and PLOD?

**Comment by kordianbruck** [comment]
@nicoladesocio no, you need to provide us a function that we call with a character name that gives us the plod for this character. Make sure you don't run the calculations each time but rather run the calc once and then cache it in a variable.

**Comment by nicoladesocio** [comment]
The function you ask requires an initialization step and and a state ,i.e an object Like this

``` javascript
function init() {}
Obj = init();
Obj.getPlod('name');

```

Is it a problemi in your integration?

**Comment by kordianbruck** [comment]
@nicoladesocio no, that should be just fine

cc @Adiolis

**Comment by AlexMoroz** [comment]
@nicoladesocio code this functions in npm.js please

```
module.exports = {
    init: function() {
         //code here
    },
    getPlod: function(name) {
        //code here
    }
}
```

**Comment by AlexMoroz** [comment]
https://github.com/Rostlab/JS16_ProjectA/issues/96
